# Generated by Django 2.2.7 on 2019-11-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.PositiveIntegerField(),
        ),
    ]
